# Generated by Django 4.2.21 on 2025-06-19 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_is_published_alter_post_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img_url',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='posts/images'),
        ),
    ]
